server:
  port: 8084

spring:
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true
  jackson:
    serialization:
      write-date-keys-as-timestamps: false
  rabbitmq:
    host: localhost
    username: user
    password: password
    port: 5672
  data:
    mongodb:
      host: localhost
      port: 29001
      username: "aliogutcen"
      password: "root"
      database: FoodProducts
jwt:
  secretKey: ${PASSWORD}